Final fix to build script plz.
Renamed run_jenkins to a more appropriate name. Jinkies!

diff --git a/Docker/build_image b/Docker/build_image
--- a/Docker/build_image
+++ b/Docker/build_image
@@ -1,15 +1,18 @@
-#!/bin/bash
-
-set -e
+#!/bin/bash -el
 
 THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 cd ${THIS_SCRIPT_DIR}
 
-if [[ ${#@} -lt 1 ]]; then
-  show_help="true"
-fi
+THIS_SCRIPT_NAME=$(basename $0)
+ENV_FILE="${THIS_SCRIPT_DIR}/build.env"
 
-ENV_FILE=build.env
+function usage() {
+  cat <<EOS
+  Usage: ${THIS_SCRIPT_NAME} - builds the container
+  Arguments:
+    -v -- Version number to tag the build with. Defaults to latest.
+EOS
+}
 
 for arg in $@
 do
@@ -20,38 +23,18 @@ do
 done
 
 if [[ "${show_help}" == "true" ]]; then
-  echo "Usage: ${0} with no arguments, builds the image."
-  echo "       ${0} --env-file /path/to/foo.env. Provides an alternate set of definitions for environment variables."
-  exit 0
-fi
-
-if [[ -f "${ENV_FILE}"]]; then
-  source "${ENV_FILE}"
-  else
-    echo "ERROR: No such variables file <${ENV_FILE}>. This must exist and be readable."
-
-NAME=$(basename $0)
-
-function usage() {
-  cat <<EOS
-  Usage: ${NAME} - builds the container
-  Arguments:
-    -v -- Version number to tag the build with. Defaults to latest.
-EOS
-}
-
-for arg in $@
-do
-  case $arg in
-    "-v"               )  shift; VERSION=$1; shift;;
-    "-h" | "--help"    )  HELP="true"; shift;;
-  esac
-done
-
-if [ ! -z "${HELP}" ]; then
   echo $(usage)
   exit 0
 fi
 
-docker build -t "${IMAGE_TAG}:${IMAGE_VERSION}" .
+if [[ -f "${ENV_FILE}" ]]; then
+  source "${ENV_FILE}"
+else
+  echo "ERROR: No such variables file <${ENV_FILE}>. This must exist and be readable."
+  exit 1
+fi
+
+docker build -t "${IMAGE_TAG}:${IMAGE_VERSION}" . --build-arg casc_jenkins_config="${CASC_JENKINS_CONFIG}" \
+                                                  --build-arg jenkins_home="${JENKINS_HOME}" \
+                                                  --build-arg jenkins_java_opts="${JENKINS_JAVA_OPTS}"
 
